#!/bin/bash
################################################################################
#                                                                              #
#   Makeit - A script to build the current package. Usage: makeit              #
#                                                                              #
#                                                                              #
################################################################################

module purge
source /apps/prod/lmodules/startLmod
module load intel/19.1.3.304  PrgEnv-intel
module load intel/19.1.3.304/cray-mpich/8.1.4
module use -a /apps/prod/modules
module load netcdf/3.6.3-intel-19.1.3.304
module list

NETCDF_LIB="$NETCDF_LIB  -lnetcdf -lnetcdf_c++"

export ESMF_F90COMPILER=mpiifort
export ESMF_F90LINKER=mpiifort

export ESMF_DIR=`pwd`

gmake check
