#%Module######################################################################
##
##    RTOFS GLO Prerequisites: Hera/Intel

proc ModulesHelp {} {
  puts stderr "\tcit - loads modules required for building RTOFS libraries on Hera/Intel"
}

module-whatis "loads RTOFS GLO libraries for Hera/Intel"

##
## load contrib environment
## load slurm utils (arbitrary.pl  layout.pl)
##
module use -a /contrib/sutils/modulefiles
module load sutils

##
## load programming environment
## this typically includes compiler, MPI and job scheduler
##
module load intel/18.0.5.274
module load impi/2018.0.4

##
## NCEP libraries 
##
module use -a /scratch2/NCEPDEV/nwprod/NCEPLIBS/modulefiles
module load w3nco/2.0.7
module load g2/3.1.1

