#%Module######################################################################
##
##    RTOFS GLO Prerequisites: Hera/Intel

proc ModulesHelp {} {
  puts stderr "\tcit - loads modules required for building RTOFS libraries on Hera/Intel"
}

module-whatis "loads RTOFS GLO libraries for Hera/Intel"

##
## load contrib environment
## load slurm utils (arbitrary.pl  layout.pl)
##
module use -a /contrib/sutils/modulefiles
module load sutils

##
## load programming environment
## this typically includes compiler, MPI and job scheduler
##
module load intel/18.0.5.274
module load impi/2018.0.4

##
## NCEP libraries 
##
module use -a /scratch2/NCEPDEV/nwprod/NCEPLIBS/modulefiles
module load bacio/2.0.3
module load w3nco/2.0.7
module load jasper/1.900.1
module load png/1.2.44
module load z/1.2.11
module load g2/3.1.1
module load w3emc/2.3.1
module load sigio/2.1.1
module load sp/2.0.3
module load bufr/11.3.0

module use -a /apps/modules/modulefamilies/intel
module load netcdf/4.6.1
module load hdf5/1.10.4

module use -a /apps/modules/modulefiles
module load ncl/6.5.0


module use -a /scratch1/NCEPDEV/nems/emc.nemspara/soft/modulefiles
module load hdf5_parallel/1.10.6
module load netcdf_parallel/4.7.4
module load esmf/8.1.0bs19_ParallelNetCDF

#mmab
#esmf

