#!/usr/bin/env python3
"""
plot_obs_stat.py

Purpose:
    Reads NCODA observation count CSV files generated by the RTOFS obs_stat pipeline
    and generates a time-series plot for a specific Observation Platform (e.g., GOES, METOP).
    It aggregates counts over time for the specified platform.

Output:
    A PNG image named 'timeseries_<obs_type>_count.png' saved in the <archive_base_path>.

Requirements:
    Python 3, pandas, matplotlib.
    On WCOSS2, load the environment before running (e.g., `module load intel ve/hafs`).
"""

import os
import sys
import glob
import argparse
import pandas as pd

# Use non-interactive backend for headless HPC environments
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

def main():
    parser = argparse.ArgumentParser(description="Plot RTOFS NCODA observation counts from CSV files.")
    parser.add_argument("archive_base_path", help="Root directory containing the YYYYMMDD subdirectories with CSVs.")
    parser.add_argument("obs_plat", help="The observation platform to plot (e.g., GOES, METOP, PROFILE). Case-insensitive.")
    
    args = parser.parse_args()

    base_path = args.archive_base_path
    obs_plat_query = args.obs_plat.lower()

    if not os.path.isdir(base_path):
        print(f"FATAL ERROR: Directory not found: {base_path}")
        sys.exit(2)

    # 1. Gather all CSV files in YYYYMMDD subdirectories
    csv_pattern = os.path.join(base_path, "20??????", "obs_counts_*.csv")
    csv_files = glob.glob(csv_pattern)

    if not csv_files:
        print(f"FATAL ERROR: No CSV files found matching {csv_pattern}")
        sys.exit(3)

    # 2. Load and concatenate data
    df_list = []
    for f in sorted(csv_files):
        try:
            df = pd.read_csv(f)
            df_list.append(df)
        except Exception as e:
            print(f"Warning: Could not read {f}: {e}")

    if not df_list:
        print("FATAL ERROR: No valid data could be loaded.")
        sys.exit(4)

    full_df = pd.concat(df_list, ignore_index=True)

    # 3. Filter by specified Obs_Plat
    df_filtered = full_df[full_df['Obs_Plat'].str.lower() == obs_plat_query].copy()

    if df_filtered.empty:
        print(f"FATAL ERROR: No data found for Obs_Plat: {obs_plat_query}")
        sys.exit(5)

    # Extract the associated Obs_Type for the filename (e.g., if plat='goes', type='SST')
    obs_type = df_filtered['Obs_Type'].iloc[0].upper()

    # 4. Standardize Date/Time
    # Pad 8-char dates (YYYYMMDD) to 10-char (YYYYMMDD00) for uniform datetime parsing
    df_filtered['Obs_Date_Str'] = df_filtered['Obs_Date'].astype(str).str.ljust(10, '0')
    df_filtered['Datetime'] = pd.to_datetime(df_filtered['Obs_Date_Str'], format='%Y%m%d%H')

    # Aggregate counts by Datetime (handling any repeated hours for the same platform)
    agg_df = df_filtered.groupby('Datetime')['Obs_Count'].sum()

    # 5. Generate Plot
    fig, ax = plt.subplots(figsize=(10, 6))
    
    ax.plot(agg_df.index, agg_df.values, marker='o', linestyle='-', label=obs_plat_query.upper())

    ax.set_title(f"RTOFS {obs_plat_query.upper()} ({obs_type}) Observation Counts")
    ax.set_xlabel("Date")
    ax.set_ylabel("Count")
    ax.grid(True, linestyle='--', alpha=0.7)
    
    # Remove top and right spines
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    # Place legend
    ax.legend(title="Platform", bbox_to_anchor=(1.05, 1), loc='upper left')

    # Format x-axis
    ax.xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d %H:%M'))
    fig.autofmt_xdate()

    plt.tight_layout()

    # Save to the base directory with lower DPI and requested filename format
    out_file = os.path.join(base_path, f"timeseries_{obs_plat_query}_{obs_type.lower()}_count.png")
    fig.savefig(out_file, dpi=120)
    print(f"SUCCESS: Plot saved to {out_file}")

    sys.exit(0)

if __name__ == "__main__":
    main()
