# Configuration file for Jmin statistics plotting
# 'Category' must match the exact string from the CSV Category column
# 'ObsType' must be a list of exact strings from the CSV Metric column

data_dir: "/lfs/h2/emc/couple/noscrub/santha.akella/RTOFS_OM/v2.5/jmin_stat"

plots:
  - Category: "Ice Cover"
    ObsType:
      - "All Data Combined"
#     - "Sea Ice"

  - Category: "Temperature"
    ObsType:
      - "All Data Combined"
      - "Argo Float Temp"
      - "SST"

  - Category: "Salinity"
    ObsType:
      - "All Data Combined"
      - "Argo Float Salt"
      - "SSS"

# - Category: "Geopotential"
#   ObsType:
#     - "All Data Combined"
