#!/bin/sh

####################################
# Ensure environment is defined.
####################################
set +x
echo cyc is ${cyc:?} 
echo envir is ${envir:?} 
echo rtofs_glo_ver is ${rtofs_glo_ver:?}

export PS4='$SECONDS + '
date
env
set -xa

#######################################
# Specify NET and RUN Name and model ID
#######################################
export NET=rtofs
export RUN=rtofs
export modID=glo
export HYCOM_EXPT=930

#####################
# SETUP RUN VARIABLES
#####################

export mycyc='00'
export cycle=t${mycyc}z

##########################################################
 # obtain unique process id (pid) and make temp directories
##########################################################
jobname=${PBS_JOBNAME}
export DATA=${DATA:-${DATAROOT}/${jobname}_${model_ver}_${envir}/${jobid}}
export DATArestart=${DATAROOT}/${jobname}_${model_ver}_${envir}/restart
export DATAarchive=${DATAROOT}/${jobname}_${model_ver}_${envir}/archive
mkdir -p $DATA
mkdir -p $DATArestart $DATAarchive
# remove archives since restart time
rm -f $DATAarchive/*
# remove restart directory since incup is too short to have multiple restart instances
rm -f $DATArestart/*
cd $DATA

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.$$"

####################################
# Specify Execution Areas
####################################
export EXECrtofs=${HOMErtofs}/exec
export PARMrtofs=${HOMErtofs}/parm
export FIXrtofs=${HOMErtofs}/fix
export USHrtofs=${HOMErtofs}/ush

#############################
# Set up the UTILITIES
##############################
export USHutil=${UTILROOT:?}/ush
export EXECutil=${UTILROOT:?}/exec
export utilexec=$EXECutil    # needed by some scripts in USHutil

###########################################################
# Run setpdy and initialize PDY variables
# For any retrospecitve run, set the PDY in the ECF script
###########################################################
setpdy.sh
. ./PDY

##############################################
# Define Input/Output/Restart directories
##############################################
export COMIN=${COMIN:-$(compath.py ${envir}/com/${NET}/${rtofs_glo_ver})/${RUN}.${PDY}}
export COMINm1=${COMINm1:-$(compath.py ${envir}/com/${NET}/${rtofs_glo_ver})/${RUN}.${PDYm1}}
export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${rtofs_glo_ver})/${RUN}.${PDY}}

mkdir -m 775 -p $COMOUT
test -d $COMOUT || mkdir -p $COMOUT

###################
# Define model grid
###################
export inputgrid=navy_0.08

##################################################################
# Run the config file to set up specific model variables if needed
##################################################################
. $PARMrtofs/${RUN}_${modID}.${inputgrid}.config

#################################################################
#  Send a message indicating the start of the job
#################################################################
msg="JOB $job HAS BEGUN on $(hostname)"
postmsg "$msg"

####################
# execute the script
####################
ksh ${HOMErtofs}/scripts/ex${RUN}_${modID}_incup.sh

#===================================================================

cat $pgmout
cp -p $pgmout $COMOUT/${RUN}_${modID}.t${cyc}z.incup.$(basename $pgmout)

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$msg"

cd $DATAROOT
if [ "$KEEPDATA" != YES ]; then
  rm -rf $DATA
  rm -rf $DATAarchive
  rm -rf $DATArestart
fi

date
