#!/bin/sh

####################################
# Ensure environment is defined.
####################################
set +x
echo cyc is ${cyc:?} 
echo envir is ${envir:?} 
echo rtofs_glo_ver is ${rtofs_glo_ver:?}

export PS4='$SECONDS + '
date
env
set -xa

#######################################
# Specify NET and RUN Name and model ID
#######################################
export NET=rtofs
export RUN=rtofs
export modID=glo
export RUN_MODE=analysis
export HYCOM_EXPT=930

export mycyc='00'
export cycle=t${mycyc}z

##########################################################
 # obtain unique process id (pid) and make temp directories
##########################################################
export DATA=${DATA:-${DATAROOT}/${jobid}}
mkdir $DATA
cd $DATA

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.$$"

####################################
# Specify Execution Areas
####################################
export HOMErtofs=${HOMErtofs:-${NWROOT:?}/${RUN}_${modID}.${rtofs_glo_ver}}
export EXECrtofs=${HOMErtofs}/exec
export PARMrtofs=${HOMErtofs}/parm
export FIXrtofs=${HOMErtofs}/fix
export USHrtofs=${HOMErtofs}/ush

#############################
# Set up the UTILITIES
##############################
export USHutil=${UTILROOT:?}/ush
export EXECutil=${UTILROOT:?}/exec
export utilexec=$EXECutil    # needed by some scripts in USHutil

###########################################################
# Run setpdy and initialize PDY variables
# For any retrospecitve run, set the PDY in the ECF script
###########################################################
setpdy.sh
. ./PDY

##############################################
# Define Input/Output/Restart directories
##############################################
export GETGES_NWG=${GETGES_NWG:-${GESROOT}}
export COMROOT=${COMROOT:-$(compath.py ${envir}/com/${NET}/${rtofs_glo_ver})}
export COMIN=${COMIN:-${COMROOT}/${RUN}.${PDY}}
export COMINm1=${COMINm1:-${COMROOT}/${RUN}.${PDYm1}}
export COMOUT=${COMOUT:-${COMROOT}/${RUN}.${PDY}}
export GESIN=${GESIN:-${GESROOTp3}/${envir}/${RUN}.${PDY}}
mkdir -m 775 -p $COMOUT
test -d $COMOUT || mkdir -p $COMOUT

###################
# Define model grid
###################
export inputgrid=navy_0.08
export useslp=NO # YES or NO, use sea level pressure

##################################################################
# Run the config file to set up specific model variables if needed
##################################################################
. $PARMrtofs/${RUN}_${modID}.${inputgrid}.config
export DBL_THKDF=NO # YES or NO

##############################################
# Check for restart
##############################################
restart_n=${RUN}_${modID}.t${cyc}z.restart_n
if [ -s $GESIN/${restart_n}*.a -a -s $GESIN/${restart_n}*.b ]
then
    export RESTART=YES
else
    export RESTART=NO
fi

#################################
# Set up analysis step parameters
#################################
eval fcstdays="\$analdays"

#################################################################
#  Send a message indicating the start of the job
#################################################################
msh="HAS BEGUN on `hostname`"
postmsg "$msg"

####################
# execute the script
####################
ksh ${HOMErtofs}/scripts/ex${RUN}_${modID}_${RUN_MODE}.sh

#===================================================================

cat $pgmout
cp -p $pgmout $COMOUT/${RUN}_${modID}.t${cyc}z.${RUN_MODE}.`basename $pgmout`

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$msg"

cd $DATAROOT
if [ "$KEEPDATA" != YES ]; then
  rm -rf $DATA
fi
date
