#!/bin/sh


####################################
# Ensure environment is defined.
####################################
set +x
echo cyc is ${cyc:?} 
echo envir is ${envir:?} 
echo model_ver is ${model_ver:?}
echo code_ver is ${code_ver:?}
echo cdo_ver is ${cdo_ver:?}

export RUN_ENVIR=${RUN_ENVIR:-prod}

set -xa

#######################################
# Specify NET and RUN Name and model ID
#######################################
export NET=rtofs
export RUN=rtofs
export modID=glo
export RUN_MODE=forecast

####################
# SETUP RUN VARIABLES
####################
if [ $RUN_ENVIR = dev ]
then
  export job=${job:-${RUN}_${modID}_${RUN_MODE}_d1-3_grib_post_${projID}}
  export NNODES=${NNODES:-1}
  export NPROCS=${NPROCS:-1}
fi

# #################################
# SETUP SHELL  PROCESSING VARIABLES
# #################################
export PATH=$PATH:.
export PS4='$SECONDS + '
date

export mycyc='00'
export cycle=t${mycyc}z

##########################################################
# obtain unique process id (pid) and make temp directories
##########################################################
export pid=$$
if [ $RUN_ENVIR = dev ]
then
   tmpdir=${tmpdir:-/ptmp/$LOGNAME/tmpdir/${projID}}
else
   tmpdir=/tmpnwprd1
fi
export DATA=$tmpdir/${job}.${pid}
test -d $DATA && rm -rf $DATA
mkdir -p $DATA
cd $DATA

####################################
# File To Log Msgs
####################################
if [ $RUN_ENVIR = dev ]
then
  export jlogfile=$HOMEout/logs/jlogfile
elif [ $RUN_ENVIR = prod -a $envir = prod ]
then
  export jlogfile=/com/logs/jlogfiles/jlogfile.${job}.${pid}
else
  export DBNROOT=/nwprod/spa_util/fakedbn
  export jlogfile=/com/logs/${envir}/jlogfile
fi
test -d `dirname $jlogfile` || mkdir -p $jlogfile


####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z

#####################################################
# SAVEGES - Copy files from TMPDIR ($DATA) to $GESdir
# SENDECF - Flag events on ECF
# SENDCOM - Copy files from TMPDIR ($DATA) to $COMOUT
# SENDDBN - Issue DBNet client calls
# RERUN   - Rerun fcst from beginning (default no)
#####################################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDDBN_NTC=${SENDDBN_NTC:-YES}
export SENDECF=${SENDECF:-YES}

####################################
# Specify Execution Areas
####################################
if [ $RUN_ENVIR = dev ]
then
  #DEV
  export HOMErtofs=$PROJECTdir
  export CODErtofs=$CODEdir
  export CDOrtofs=$CDOdir
else
  #NCO
  export HOMErtofs=/nw${envir}/${RUN}_${modID}.${model_ver}
  export CODErtofs=/nw${envir}/${RUN}_code.${code_ver}
  export CDOrtofs=/nw${envir}/${RUN}_shared/${RUN}_cdo.${cdo_ver}
fi
export EXECrtofs=${HOMErtofs}/exec
export PARMrtofs=${HOMErtofs}/parm
export FIXrtofs=${HOMErtofs}/fix
export USHrtofs=${HOMErtofs}/ush
export EXECcode=${CODErtofs}/exec
export cdo_r=${CDOrtofs}/bin/cdo

#############################
# Set up the UTILITIES
##############################
export utilscript=/nwprod/util/ush
export utilexec=/nwprod/util/exec

#################################################################
# Run setup to initialize working directory and utility scripts
#################################################################
sh $utilscript/setup.sh

###########################################################
# Run setpdy and initialize PDY variables
# For any retrospecitve run, set the PDY in the ECF script
###########################################################
export PDY=${PDY:-}
sh $utilscript/setpdy.sh
. PDY

###################
# Define model gird
###################
export inputgrid=navy_0.08

##################################################################
# Run the config file to set up specific model variables if needed
##################################################################
. $PARMrtofs/${RUN}_${modID}.${inputgrid}.config

##############################################
# Define Input/Output/Restart directories
##############################################
if [ $RUN_ENVIR = dev ]
then
  export COMIN=${COMIN:-${HOMEout}/${NET}/${RUN}.${PDY}}
  export COMOUT=${COMOUT:-${HOMEout}/${NET}/${RUN}.${PDY}}
  export GESdir=${HOMEout}/${NET}/nwges/${RUN}.${PDY}
else
  export COMIN=/com/${NET}/${envir}/${RUN}.${PDY}
  export COMOUT=/com/${NET}/${envir}/${RUN}.${PDY}
  export GESdir=/nwges/${envir}/${RUN}.${PDY}
fi

if [ $envir = prod ]; then
    export pcom=/pcom/rtofs
else
    export pcom=/pcom/${envir}/rtofs
fi

test -d $GESdir || mkdir -m 775 -p $GESdir
test -d $COMOUT || mkdir -m 775 -p $COMOUT
test -d $pcom || mkdir -m 775 -p $pcom

############################################
# Set up forecast post-processing parameters
############################################
## This assumes that the $job has the name structure of the type job_*NN
## where NN is two-digit number
export postday=`echo $job | rev |cut -c1-2 | rev`
export digitest=`echo $postday |cut -c1`
if [ $digitest -eq 0 ]; then
  export postday=`echo $postday|cut -c2`
fi
export startdate=`${utilexec}/ndate \`expr 24 \* \( $postday \- 1 \) \` $PDY$mycyc |cut -c1-8`
#export startdate=${startdate:-${PDY}}
export fcstdays_before_thisstep=` expr \` $utilexec/nhour $startdate$mycyc $PDY$mycyc \` \/ 24 `
if [ ${fcstdays_before_thisstep} -lt 3 ]
then
  eval fcstdays="\$fcst_post_ndays"
else
  fcstdays=3
fi
export fcstdays


export MP_CSS_INTERRUPT=yes
unset MP_POLLING_INTERVAL
env
################################################################
# Send a message to the jlogfile indicating the start of the job
################################################################
msg="HAS BEGUN on `hostname`"
postmsg "$jlogfile" "$msg"

####################
# execute the script
####################
ksh ${HOMErtofs}/scripts/exrtofs_glo_grib2_post.sh.ecf

cat $pgmout
cp -p $pgmout $COMOUT/${RUN}_${modID}.t${cyc}z.forecast_d1-3_grib_post.`basename $pgmout`

msg="JOB $job HAS COMPLETED NORMALLY." 
postmsg "$jlogfile" "$msg"


cd $tmpdir
### rm -rf $DATA

date
