#!/bin/bash
#PBS -N rtofs_forecast
#PBS -j oe
#PBS -A RTOFS-DEV
#PBS -W umask=027
#PBS -l place=vscatter:exclhost,select=15:ncpus=120:mpiprocs=120
#PBS -q dev
#PBS -l walltime=001:00:00
##PBS -l debug=true
#PBS -V

module purge
module load envvar
module load prod_envir
module load prod_util
module load PrgEnv-intel/8.3.3
module load craype/2.7.17
module load intel/19.1.3.304
module load cray-pals/1.0.17
module load cray-mpich/8.1.19
module load cfp/2.0.4
module load netcdf/3.6.3
module load hdf5/1.10.6
module list

export FI_OFI_RXM_BUFFER_SIZE=128000
export FI_OFI_RXM_RX_SIZE=64000
export NPROCS=1800
export OMP_NUM_THREADS=1

# -- Set following 2 lines:
run_date=2029MMDD
ptmp_path=/lfs/h2/emc/ptmp/santha.akella/
# --

exp_dir=${ptmp_path}/rtofs.${run_date}
cd ${exp_dir}
echo "Path: "${exp_dir}
# --

# USE Dan's exec- he gave path to it on 04/11/2025.
mpiexec -np 1800 --cpu-bind verbose,core /lfs/h2/emc/eib/save/dan.iredell/rtofs.v2.5.REL1/exec/rtofs_hycom

# Missing a check!
#exit 0
